[package]
name = "merge-sorted-files-rs"
version = "0.1.0"
authors = ["Ben Cohen <ben@cohen-family.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
